<?php

return [

   /*
   |--------------------------------------------------------------------------
   | Last Minute Extra Types
   |--------------------------------------------------------------------------
   |
   | Here you may specify the school years supported by the application.
   | (only for EHL now)
   | Used for selects templating.
   |
   */
  'last_minute_types' => [
     'Service en restaurant',
     'Réception',
     'Housekeeping',
     'Cuisine',
     'Barman',
     'Plonge',
     'Banquet',
     'Sommellerie',
     'Autre',
  ],

   /*
   |--------------------------------------------------------------------------
   | Professionals categories
   |--------------------------------------------------------------------------
   |
   | Here you may specify the school years supported by the application.
   | (only for EHL now)
   | Used for selects templating.
   |
   */
  'professionals_categories' => [
     'Hôtel',
     'Restaurant',
     'Boite de Nuit',
     'Bar',
     'Ecole Hôtelière',
     'Autre',
  ],

    /*
    |--------------------------------------------------------------------------
    | EHL school years
    |--------------------------------------------------------------------------
    |
    | Here you may specify the school years supported by the application.
    | (only for EHL now)
    | Used for selects templating.
    |
    */
   'ehl_years' => [
      'AP',
      'BOSC 1',
      'BOSC 2',
      'BOSC 3',
      'BOSC 4',
      'BOSC 5',
      'BOSC 6',
   ],

    /*
    |--------------------------------------------------------------------------
    | Countries supported
    |--------------------------------------------------------------------------
    |
    | Here you may specify the countries supported by the application.
    | Used for selects templating.
    |
    */

   'countries' => [
      'Afghanistan',
      'Åland Islands',
      'Albania',
      'Algeria',
      'American Samoa',
      'Andorra',
      'Angola',
      'Anguilla',
      'Antarctica',
      'Antigua and Barbuda',
      'Argentina',
      'Armenia',
      'Aruba',
      'Australia',
      'Austria',
      'Azerbaijan',
      'Bahamas',
      'Bahrain',
      'Bangladesh',
      'Barbados',
      'Belarus',
      'Belgium',
      'Belize',
      'Benin',
      'Bermuda',
      'Bhutan',
      'Bolivia (Plurinational State of)',
      'Bonaire, Sint Eustatius and Saba',
      'Bosnia and Herzegovina',
      'Botswana',
      'Bouvet Island',
      'Brazil',
      'British Indian Ocean Territory',
      'Brunei Darussalam',
      'Bulgaria',
      'Burkina Faso',
      'Burundi',
      'Cambodia',
      'Cameroon',
      'Canada',
      'Cabo Verde',
      'Cayman Islands',
      'Central African Republic',
      'Chad',
      'Chile',
      'China',
      'Christmas Island',
      'Cocos (Keeling) Islands',
      'Colombia',
      'Comoros',
      'Congo',
      'Congo (Democratic Republic of the)',
      'Cook Islands',
      'Costa Rica',
      'Côte d\'Ivoire',
      'Croatia',
      'Cuba',
      'Curaçao',
      'Cyprus',
      'Czech Republic',
      'Denmark',
      'Djibouti',
      'Dominica',
      'Dominican Republic',
      'Ecuador',
      'Egypt',
      'El Salvador',
      'Equatorial Guinea',
      'Eritrea',
      'Estonia',
      'Ethiopia',
      'Falkland Islands (Malvinas)',
      'Faroe Islands',
      'Fiji',
      'Finland',
      'France',
      'French Guiana',
      'French Polynesia',
      'French Southern Territories',
      'Gabon',
      'Gambia',
      'Georgia',
      'Germany',
      'Ghana',
      'Gibraltar',
      'Greece',
      'Greenland',
      'Grenada',
      'Guadeloupe',
      'Guam',
      'Guatemala',
      'Guernsey',
      'Guinea',
      'Guinea-Bissau',
      'Guyana',
      'Haiti',
      'Heard Island and McDonald Islands',
      'Holy See',
      'Honduras',
      'Hong Kong',
      'Hungary',
      'Iceland',
      'India',
      'Indonesia',
      'Iran (Islamic Republic of)',
      'Iraq',
      'Ireland',
      'Isle of Man',
      'Israel',
      'Italy',
      'Jamaica',
      'Japan',
      'Jersey',
      'Jordan',
      'Kazakhstan',
      'Kenya',
      'Kiribati',
      'Korea (Democratic People\'s Republic of)',
      'Korea (Republic of)',
      'Kuwait',
      'Kyrgyzstan',
      'Lao People\'s Democratic Republic',
      'Latvia',
      'Lebanon',
      'Lesotho',
      'Liberia',
      'Libya',
      'Liechtenstein',
      'Lithuania',
      'Luxembourg',
      'Macao',
      'Macedonia (the former Yugoslav Republic of)',
      'Madagascar',
      'Malawi',
      'Malaysia',
      'Maldives', 'Mali',
      'Malta',
      'Marshall Islands',
      'Martinique',
      'Mauritania',
      'Mauritius',
      'Mayotte',
      'Mexico',
      'Micronesia (Federated States of)',
      'Moldova (Republic of)',
      'Monaco',
      'Mongolia',
      'Montenegro',
      'Montserrat',
      'Morocco',
      'Mozambique',
      'Myanmar',
      'Namibia',
      'Nauru',
      'Nepal',
      'Netherlands',
      'New Caledonia',
      'New Zealand',
      'Nicaragua',
      'Niger',
      'Nigeria',
      'Niue',
      'Norfolk Island',
      'Northern Mariana Islands',
      'Norway',
      'Oman',
      'Pakistan',
      'Palau',
      'Palestine, State of',
      'Panama',
      'Papua New Guinea',
      'Paraguay',
      'Peru',
      'Philippines',
      'Pitcairn',
      'Poland',
      'Portugal',
      'Puerto Rico',
      'Qatar',
      'Réunion',
      'Romania',
      'Russian Federation',
      'Rwanda',
      'Saint Barthélemy',
      'Saint Helena, Ascension and Tristan da Cunha',
      'Saint Kitts and Nevis',
      'Saint Lucia',
      'Saint Martin (French part)',
      'Saint Pierre and Miquelon',
      'Saint Vincent and the Grenadines',
      'Samoa',
      'San Marino',
      'Sao Tome and Principe',
      'Saudi Arabia',
      'Senegal',
      'Serbia',
      'Seychelles',
      'Sierra Leone',
      'Singapore',
      'Sint Maarten (Dutch part)',
      'Slovakia',
      'Slovenia',
      'Solomon Islands',
      'Somalia',
      'South Africa',
      'South Georgia and the South Sandwich Islands',
      'South Sudan',
      'Spain',
      'Sri Lanka',
      'Sudan',
      'Suriname',
      'Svalbard and Jan Mayen',
      'Swaziland',
      'Sweden',
      'Switzerland',
      'Syrian Arab Republic',
      'Taiwan, Province of China',
      'Tajikistan',
      'Tanzania, United Republic of',
      'Thailand',
      'Timor-Leste',
      'Togo',
      'Tokelau',
      'Tonga',
      'Trinidad and Tobago',
      'Tunisia',
      'Turkey',
      'Turkmenistan',
      'Turks and Caicos Islands',
      'Tuvalu',
      'Uganda',
      'Ukraine',
      'United Arab Emirates',
      'United Kingdom',
      'United States of America',
      'United States Minor Outlying Islands',
      'Uruguay',
      'Uzbekistan',
      'Vanuatu',
      'Venezuela (Bolivarian Republic of)',
      'Viet Nam',
      'Virgin Islands (British)',
      'Virgin Islands (U.S.)',
      'Wallis and Futuna',
      'Western Sahara',
      'Yemen',
      'Zambia',
      'Zimbabwe'
   ],

   'nationalities' => [
      'Afghans',
      'Albanians',
      'Algerians',
      'Americans',
      'Andorrans',
      'Angolans',
      'Argentines',
      'Armenians',
      'Aromanians',
      'Arubans',
      'Australians',
      'Austrians',
      'Azeris',
      'Bahamians',
      'Bahrainis',
      'Bangladeshis',
      'Barbadians',
      'Belarusians',
      'Belgians',
      'Belizeans',
      'Bermudians',
      'Boers',
      'Bosniaks',
      'Brazilians',
      'Bretons',
      'British',
      'British Virgin Islanders',
      'Bulgarians',
      'Burmeses',
      'Macedonian Bulgarians',
      'Burkinabès',
      'Burundians',
      'Cambodians',
      'Cameroonians',
      'Canadians',
      'Catalans',
      'Cape Verdeans',
      'Chadians',
      'Chileans',
      'Chinese',
      'Colombians',
      'Comorians',
      'Congolese',
      'Croatians',
      'Cubans',
      'Cypriots',
      'Turkish Cypriots',
      'Czechs',
      'Danes',
      'Dominicans',
      'Dominicans',
      'Dutch',
      'East Timorese',
      'Ecuadorians',
      'Egyptians',
      'Emiratis',
      'English',
      'Eritreans',
      'Estonians',
      'Ethiopians',
      'Faroese',
      'Finns',
      'Finnish Swedish',
      'Fijians',
      'Filipinos',
      'French',
      'Georgians',
      'Germans',
      'Baltic Germans',
      'Ghanaians',
      'Gibraltar',
      'Greeks',
      'Greek Macedonians',
      'Grenadians',
      'Guatemalans',
      'Guianese (French)',
      'Guineans',
      'Guinea-Bissau nationals',
      'Guyanese',
      'Haitians',
      'Hondurans',
      'Hong Kong',
      'Hungarians',
      'Icelanders',
      'I-Kiribati',
      'Indians',
      'Indonesians',
      'Iranians (Persians)',
      'Iraqis',
      'Irish',
      'Israelis',
      'Italians',
      'Ivoirians',
      'Jamaicans',
      'Japanese',
      'Jordanians',
      'Kazakhs',
      'Kenyans',
      'Koreans',
      'Kosovo Albanians',
      'Kurds',
      'Kuwaitis',
      'Kyrgyzs',
      'Lao',
      'Latvians',
      'Lebanese',
      'Liberians',
      'Libyans',
      'Liechtensteiners',
      'Lithuanians',
      'Luxembourgers',
      'Macedonians',
      'Malagasy',
      'Malaysians',
      'Malawians',
      'Maldivians',
      'Malians',
      'Maltese',
      'Manx',
      'Mauritians',
      'Mexicans',
      'Moldovans',
      'Moroccans',
      'Mongolians',
      'Montenegrins',
      'Namibians',
      'Nepalese',
      'New Zealanders',
      'Nicaraguans',
      'Nigeriens',
      'Nigerians',
      'Norwegians',
      'Pakistanis',
      'Palauans',
      'Palestinians',
      'Panamanians',
      'Papua New Guineans',
      'Paraguayans',
      'Peruvians',
      'Poles',
      'Portuguese',
      'Puerto Ricans',
      'Quebecers',
      'Réunionnais',
      'Romanians',
      'Russians',
      'Baltic Russians',
      'Rwandans',
      'Salvadorans',
      'São Tomé and Príncipe',
      'Saudis',
      'Scots',
      'Senegalese',
      'Serbs',
      'Sierra Leoneans',
      'Singaporeans',
      'Sindhian',
      'Slovaks',
      'Slovenes',
      'Somalis',
      'South Africans',
      'Spaniards',
      'Sri Lankans',
      'St Lucians',
      'Sudanese',
      'Surinamese',
      'Swedes',
      'Swiss',
      'Syriacs',
      'Syrians',
      'Taiwanese',
      'Tanzanians',
      'Thais',
      'Tibetans',
      'Tobagonians',
      'Trinidadians',
      'Tunisians',
      'Turks',
      'Tuvaluans',
      'Ugandans',
      'Ukrainians',
      'Uruguayans',
      'Uzbeks',
      'Vanuatuans',
      'Venezuelans',
      'Vietnamese',
      'Welsh',
      'Yemenis',
      'Zambians',
      'Zimbabweans'
   ]


];
